
name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build API
        shell: bash
        run: |
          chmod u+x * && sudo ./remove-github-repos.sh
